---
- hosts: all
  gather_facts: false # As Python is not yet installed, we cannot gather host facts

  tasks:
    - name: Check python installed
      raw: "python -V"      
      register: output
      changed_when: false

    - name: Apt update
      raw: "apt-get -y update"
      become: true
      retries: 10
      delay: 20
      when: output.rc != 0

    - name: Install Python
      raw: "apt-get -y -q install python"
      become: true
      retries: 10
      delay: 20
      when: output.rc != 0